### ISSUE TITLE
Create Account Parent | Route

### ISSUE THREAD

**Issue by asem1789** [GSG-G7/Parent-assistent#15]
## Sign Up page

- [ ] UI
- [ ] Validation
- [ ] Validation schema
- [ ] Sign Up

<hr>

### **UI**

<br>

![signUp](https://user-images.githubusercontent.com/40121654/65272892-a54d6b80-db28-11e9-9c48-e39ceb3aed6e.PNG)

<hr>

### **Validation**

All input will be validate for any unwanted data

<hr>

### **Validation schema**

<br>

```
  {
    email: String,
    username: String,
    parentid: String,
    password: String,
    confirmpassword: String,
  }
```

<br>
<hr>

### **Sign up Button**

will send request to backEnd to add new user as a parent

**Comment by aminalakhsham** [comment]
this page needs validation and schem for validation 
and explains what the signup button do 
@asem1789
