### ISSUE TITLE
Backend Route | signup/parent

### ISSUE THREAD

**Issue by Asmaathabet** [GSG-G7/Parent-assistent#37]
#### Method : POST 

---

#### Main Things : 
- [x] Validation
- [x] Hashing password 
- [x] Database
- [x] Response
- [x] Test

---
#### Validation : 
 The body of the request must match the entered  schema for validation such as : 
 ```
 {
    email : string , email 
    username : string, min[3]
    parentId: integer
    password : string , [a-zA-Z0-9] , min:[6]
 }
 ```
---
#### Hashing password: 
 After doing Validation , the password must be hashed by bcrypt before sending it to the database.

---

#### Database :
All entered data will be inserted to two tables users & parent tables in the database .

---
#### Response : 
Response may be success or error :
* Error :
```
    {
    error: "bad request",
    "Status-Code": 400
    }
```
* Success
```
    {
    data:
    {
    email : string, email 
    username : string, min[3]
    parentId: integer
    } , 
    "Status-Code": 200    
    }
```
---
#### Test : 
* Route : 
  Test route by testing all the expected cases for sign up.
  
* Query : 
  Test signup database query to make sure that it insert right data with out any injections.

**Comment by Mohammed-Q96** [comment]
Tow other scenarios 
- [ ] check for existing user name 

- [ ] check for valdation error
