### ISSUE TITLE
Do not copy properties into state

### ISSUE THREAD

**Issue by 11janci** [GSG-G7/Parent-assistent#83]
In the [Header](client/src/components/common/Header/index.js) component, the state is initialized like this
```
constructor(props) {
    super(props);
    const { auth } = this.props;
    this.state = {
      show: false,
      isSigned: auth,
    };
  }
```
The `isSigned` property is not updated anywhere outside of the constructor. This means that it will be set only once when the component is created and won't change again, even when the `auth` property changes! This is why putting properties into state is bad practice.

AC:

- [ ] remove `isSigned` from the state completely and use directly the value from the properties
- [ ] rename `auth` in the properties to `isSigned` (will have to update where the component is used, but should be just a few - one? - place)
- [ ] remove the constructor altogether and use class state initialization (cleaner code):
```
class Header extends Component {
    state = {
        show: false
    }
```
- [ ] change the component to [PureComponent](https://stackoverflow.com/questions/41340697/react-component-vs-react-purecomponent/53740921)

**Comment by aminalakhsham** [comment]
this is my fault and i see it today.
I put it in mind to change it.
thank you for writing it as an issue :sweat_smile:

**Comment by 11janci** [comment]
> this is my fault and i see it today.
> I put it in mind to change it.
> thank you for writing it as an issue 😅

no worries! :)
